<?xml version="1.0" encoding="UTF-8"?>
<!--

    Elemental
    Copyright (C) 2024, Evolved Binary Ltd

    admin@evolvedbinary.com
    https://www.evolvedbinary.com | https://www.elemental.xyz

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; version 2.1.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

    NOTE: Parts of this file contain code from 'The eXist-db Authors'.
          The original license header is included below.

    =====================================================================

    eXist-db Open Source Native XML Database
    Copyright (C) 2001 The eXist-db Authors

    info@exist-db.org
    http://www.exist-db.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>xyz.elemental.fork.org.exist-db</groupId>
        <artifactId>exist-parent</artifactId>
        <version>7.7.0</version>
        <relativePath>../exist-parent</relativePath>
    </parent>

    <artifactId>exist-ant</artifactId>
    <packaging>jar</packaging>

    <name>eXist-db Ant Tasks</name>
    <description>Ant Tasks for eXist-db NoSQL Database Client/Server</description>

    <scm>
        <connection>scm:git:https://github.com/evolvedbinary/elemental.git</connection>
        <developerConnection>scm:git:https://github.com/evolvedbinary/elemental.git</developerConnection>
        <url>scm:git:https://github.com/evolvedbinary/elemental.git</url>
      <tag>elemental-7.7.0</tag>
  </scm>

    <dependencies>
        <dependency>
            <groupId>xyz.elemental.fork.org.exist-db</groupId>
            <artifactId>exist-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>xyz.elemental.fork.org.exist-db</groupId>
            <artifactId>exist-start</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>xyz.elemental</groupId>
            <artifactId>elemental-media-type-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>xyz.elemental</groupId>
            <artifactId>elemental-media-type-impl</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>net.sf.xmldb-org</groupId>
            <artifactId>xmldb-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant</artifactId>
        </dependency>
        <dependency>
            <groupId>com.evolvedbinary.thirdparty.xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <!-- we ourselves have a test scoped dependency on a newer hamcrest... see below! -->
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.ant</groupId>
            <artifactId>ant-testutil</artifactId>
            <version>${ant.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
            </testResource>
            <testResource>
                <directory>src/test/resources-filtered</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <licenseSets>

                        <licenseSet>
                            <!--
                                Elemental License - (LGPL 2.1 only)
                            -->
                            <header>${project.parent.relativePath}/../elemental-parent/elemental-LGPL-21-ONLY-license.template.txt</header>
                            <excludes>
                                <exclude>pom.xml</exclude>
                                <exclude>src/**</exclude>
                            </excludes>
                        </licenseSet>

                        <licenseSet>
                            <!--
                                Combined: Elemental License (LGPL 2.1 only) + eXist-db License (LGPL 2.1 or later)
                            -->
                            <multi>
                                <header>${project.parent.relativePath}/../elemental-parent/elemental-LGPL-21-ONLY-license.template.txt</header>
                                <separator><![CDATA[NOTE: Parts of this file contain code from 'The eXist-db Authors'.
      The original license header is included below.

=====================================================================
                                        ]]></separator>
                                <header>${project.parent.relativePath}/../exist-parent/existdb-LGPL-21-license.template.txt</header>
                            </multi>
                            <includes>
                                <include>pom.xml</include>
                                <include>src/test/resources-filtered/conf.xml</include>
                                <include>src/test/resources/log4j2.xml</include>
                                <include>src/main/java/org/exist/ant/AbstractXMLDBTask.java</include>
                                <include>src/main/java/org/exist/ant/AddGroupTask.java</include>
                                <include>src/main/java/org/exist/ant/AddUserTask.java</include>
                                <include>src/main/java/org/exist/ant/ChmodTask.java</include>
                                <include>src/main/java/org/exist/ant/ChownTask.java</include>
                                <include>src/test/java/org/exist/ant/FileTaskTest.java</include>
                                <include>src/main/java/org/exist/ant/ListGroupsTask.java</include>
                                <include>src/main/java/org/exist/ant/ListUsersTask.java</include>
                                <include>src/main/java/org/exist/ant/LockResourceTask.java</include>
                                <include>src/main/java/org/exist/ant/RemoveGroupTask.java</include>
                                <include>src/main/java/org/exist/ant/RemoveUserTask.java</include>
                                <include>src/main/java/org/exist/ant/RestoreTask.java</include>
                                <include>src/test/java/org/exist/ant/ServerTaskTest.java</include>
                                <include>src/main/java/org/exist/ant/UserPasswordTask.java</include>
                                <include>src/main/java/org/exist/ant/UserTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBCopyTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBCreateTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBExistTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBExtractTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBListTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBMoveTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBRemoveTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBShutdownTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBStoreTask.java</include>
                                <include>src/test/java/org/exist/ant/XmldbTaskTest.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBXPathTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBXQueryTask.java</include>
                                <include>src/main/java/org/exist/ant/XMLDBXUpdateTask.java</include>
                            </includes>
                        </licenseSet>

                        <licenseSet>
                            <!--
                                eXist-db License (LGPL 2.1 or later)
                            -->
                            <header>${project.parent.relativePath}/../exist-parent/existdb-LGPL-21-license.template.txt</header>
                            <excludes>
                                <exclude>**.md</exclude>
                                <exclude>**.txt</exclude>
                                <exclude>**.xar</exclude>
                                <exclude>**LICENSE</exclude>
                                <exclude>pom.xml</exclude>
                                <exclude>xquery-license-style.xml</exclude>
                                <exclude>src/test/resources-filtered/conf.xml</exclude>
                                <exclude>src/test/resources/log4j2.xml</exclude>
                                <exclude>src/main/java/org/exist/ant/AbstractXMLDBTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/AddGroupTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/AddUserTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/ChmodTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/ChownTask.java</exclude>
                                <exclude>src/test/java/org/exist/ant/FileTaskTest.java</exclude>
                                <exclude>src/main/java/org/exist/ant/ListGroupsTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/ListUsersTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/LockResourceTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/RemoveGroupTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/RemoveUserTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/RestoreTask.java</exclude>
                                <exclude>src/test/java/org/exist/ant/ServerTaskTest.java</exclude>
                                <exclude>src/main/java/org/exist/ant/UserPasswordTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/UserTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBCopyTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBCreateTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBExistTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBExtractTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBListTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBMoveTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBRemoveTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBShutdownTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBStoreTask.java</exclude>
                                <exclude>src/test/java/org/exist/ant/XmldbTaskTest.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBXPathTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBXQueryTask.java</exclude>
                                <exclude>src/main/java/org/exist/ant/XMLDBXUpdateTask.java</exclude>
                            </excludes>
                        </licenseSet>
                    </licenseSets>
                </configuration>
            </plugin>
        </plugins>

    </build>

</project>