name: 'install-mvnd'
description: 'Install the maven daemon'
inputs:
  version:
    description: 'The version of the maven daemon to install'
    required: true
    default: '0.9.0'
outputs:
  mvnd-dir:
    description: "The directory where the command mvnd is located"
    value: ${{ steps.mvnd-location.outputs.mvnd-dir }}
runs:
  using: "composite"
  steps:
    - name: Download mvnd (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        curl -fsSL -o mvnd.zip https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-linux-amd64.zip
        curl -fsSL -o mvnd.zip.sha256 https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-linux-amd64.zip.sha256
    - name: Download mvnd (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl -fsSL -o mvnd.zip https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-darwin-amd64.zip
        curl -fsSL -o mvnd.zip.sha256 https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-darwin-amd64.zip.sha256
    - name: Download mvnd (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        curl -fsSL -o mvnd.zip https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-windows-amd64.zip
        curl -fsSL -o mvnd.zip.sha256 https://archive.apache.org/dist/maven/mvnd/${{ inputs.version }}/maven-mvnd-${{ inputs.version }}-windows-amd64.zip.sha256
    - name: Install sha256sum (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install coreutils
    - name: Verify sha256sum
      shell: bash
      run: echo "$(cat mvnd.zip.sha256) mvnd.zip" | sha256sum --check
    - name: Unzip mvnd
      shell: bash
      run: unzip mvnd.zip -d /tmp/
    - id: mvnd-location
      shell: bash
      run: |
        MVND_BIN_DIR="$(find /tmp/ -maxdepth 1 -name 'maven-mvnd-${{ inputs.version }}-*-amd64' -type d)/bin"
        if [ "$RUNNER_OS" == "Windows" ]; then
          MVND_BIN_DIR="$(cygpath --absolute --long-name --windows $MVND_BIN_DIR)"
        fi
        echo "mvnd-dir=${MVND_BIN_DIR}" >> $GITHUB_OUTPUT
