<?xml version="1.0" encoding="UTF-8"?>
<!--

    Elemental
    Copyright (C) 2024, Evolved Binary Ltd

    admin@evolvedbinary.com
    https://www.evolvedbinary.com | https://www.elemental.xyz

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; version 2.1.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>xyz.elemental</groupId>
        <artifactId>elemental-parent</artifactId>
        <version>7.4.1</version>
        <relativePath>../elemental-parent</relativePath>
    </parent>

    <artifactId>exist-core-build-tools</artifactId>
    <packaging>jar</packaging>

    <name>eXist-db Core Build Tools</name>
    <description>Tools for building exist-core</description>

    <scm>
        <connection>scm:git:https://github.com/evolvedbinary/elemental.git</connection>
        <developerConnection>scm:git:https://github.com/evolvedbinary/elemental.git</developerConnection>
        <url>scm:git:https://github.com/evolvedbinary/elemental.git</url>
        <tag>elemental-7.4.1</tag>
    </scm>

    <dependencies>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
        <!--
        <dependency>
            <groupId>com.palantir.javapoet</groupId>
            <artifactId>javapoet</artifactId>
            <version>0.7.0</version>
        </dependency>
        -->
        <dependency>
            <groupId>com.squareup</groupId>
            <artifactId>javapoet</artifactId>
            <version>1.13.0</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <licenseSets>
                        <licenseSet>
                            <!--
                                Elemental License - (LGPL 2.1 only)
                            -->
                            <header>${project.parent.relativePath}/elemental-LGPL-21-ONLY-license.template.txt</header>
                            <includes>
                                <include>src/main/java/xyz/elemental/build/tools/spoon/processors/PermissionRequiredProcessor.java</include>
                            </includes>
                        </licenseSet>
                    </licenseSets>
                </configuration>
                <executions>
                    <execution>
                        <id>check-headers</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <!--
                        NOTE(AR) needed so that we don't try and process ourselves
                            i.e. the META-INF/services/javax.annotation.processing.Processor defined in this project
                     -->
                    <proc>none</proc>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>