#
# Elemental
# Copyright (C) 2024, Evolved Binary Ltd
#
# admin@evolvedbinary.com
# https://www.evolvedbinary.com | https://www.elemental.xyz
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; version 2.1.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

### START: Container build time args for Elemental Server
##
# Elemental data cache size
ARG ELEMENTAL_SERVER_CACHE_MEM="256"
# Elemental maximum number of database brokers
ARG ELEMENTAL_SERVER_MAX_BROKER="20"
##
### END: Container build time args for Elemental Server

### START: Container build time args for JVM (Java Virtual Machine)
##
# JVM maximum RAM use (as a percentage of RAM available to the Docker Container)
ARG JVM_MAX_RAM_PERCENTAGE="75.0"

# JVM debugging protocol, suspend process on startup (y = Yes, n = No)
ARG JVM_JDWP_SUSPEND="n"
# JVM debugging protocol address and/or port
ARG JVM_JDWP_ADDRESS="5005"

# Any additional options to be added to the JAVA_TOOL_OPTIONS Environment Variable for the JVM
ARG ADDITIONAL_JAVA_TOOL_OPTIONS
##
### END: Container build time args for JVM (Java Virtual Machine)


# Use Chainguard Wolfi
FROM cgr.dev/chainguard/wolfi-base

# Inherit global args to this build stage
ARG ELEMENTAL_SERVER_CACHE_MEM
ARG ELEMENTAL_SERVER_MAX_BROKER
ARG JVM_MAX_RAM_PERCENTAGE
ARG JVM_JDWP_SUSPEND
ARG JVM_JDWP_ADDRESS
ARG ADDITIONAL_JAVA_TOOL_OPTIONS

RUN apk update && apk upgrade
# Install dependencies needed for JDK
RUN apk add tzdata zlib libjpeg-turbo libpng lcms2 freetype ttf-dejavu fontconfig-config libfontconfig1 expat libuuid libbrotlicommon1 libbrotlidec1 libbrotlienc1 libcrypt1
# Install latest CA certificates
RUN apk add ca-certificates java-cacerts
# Install latest JDK
RUN apk add openjdk-8

# Switch to nonroot user
USER nonroot

# Copy Elemental
COPY LICENSE /elemental/LICENSE
COPY autodeploy /elemental/autodeploy
COPY etc /elemental/etc
COPY lib /elemental/lib
COPY --chown=nonroot logs /elemental/logs
COPY --chown=nonroot logs /elemental/data

# Build-time metadata as defined at http://label-schema.org
# and used by autobuilder @hooks/build
LABEL org.label-schema.build-date=${maven.build.timestamp} \
      org.label-schema.description="Elemental - NoSQL Database (DEBUG version)" \
      org.label-schema.name="elemental-debug" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.url="${project.url}" \
      org.label-schema.vcs-ref=${build-commit-abbrev} \
      org.label-schema.vcs-url="${project.scm.url}" \
      org.label-schema.vendor="${project.organization.name}"

EXPOSE 8080 8443 5005

ENV ELEMENTAL_HOME="/elemental"
ENV EXIST_HOME="/elemental"
ENV CLASSPATH="/elemental/lib/${elemental.uber.jar.filename}"

ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"

ENV JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8 -Dsun.jnu.encoding=UTF-8 -Djava.awt.headless=true -Dorg.exist.db-connection.cacheSize=${ELEMENTAL_SERVER_CACHE_MEM}M -Dorg.exist.db-connection.pool.max=${ELEMENTAL_SERVER_MAX_BROKER} -Dlog4j.configurationFile=/elemental/etc/log4j2.xml -Dexist.home=/elemental -Dexist.configurationFile=/elemental/etc/conf.xml -Djetty.home=/elemental -Dexist.jetty.config=/elemental/etc/jetty/standard.enabled-jetty-configs -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseContainerSupport -XX:MaxRAMPercentage=${JVM_MAX_RAM_PERCENTAGE} -XX:+ExitOnOutOfMemoryError -agentlib:jdwp=transport=dt_socket,server=y,suspend=${JVM_JDWP_SUSPEND},address=${JVM_JDWP_ADDRESS} ${ADDITIONAL_JAVA_TOOL_OPTIONS}"

ENV PATH="/usr/lib/jvm/java-1.8-openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

HEALTHCHECK CMD [ "java", \
    "org.exist.start.Main", "client", \
    "--no-gui",  \
    "--user", "guest", "--password", "guest", \
    "--xpath", "system:get-version()" ]

CMD [ "java", \
    "org.exist.start.Main", "jetty" ]
