name: Deploy
on: [push, pull_request]
jobs:
  deploy:
    name: Publishing docker images
    runs-on: ubuntu-latest
    if: ${{ github.ref == ('refs/heads/develop' || 'refs/heads/master') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      # TODO(DP): reuse artefacts from Build step
      - name: Maven Build
        run: mvn -V -B -q -T 2C -P \!mac-dmg-on-mac,\!codesign-mac-dmg,\!mac-dmg-on-unix,\!installer clean package -DskipTests -Ddependency-check.skip=true -Ddocker=true
      - name: Build and push latest images
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: $ {{ secrets.DOCKER_PASSWORD }}
        run: |
          cd exist-docker
          mvn -DskipTests -Ddocker.tag=latest -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push
          cd ..
      - name: Build and push release images
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: $ {{ secrets.DOCKER_PASSWORD }}
        run: |
          cd exist-docker
          mvn -DskipTests -Ddocker.tag=release -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:build docker:push
          cd ..       