name: XQTS
on: [push, pull_request]
permissions:
  contents: read

jobs:
  xqts:
    name: W3C XQuery Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Maven XQTS Build
        run: mvn -V -B clean package -DskipTests -Ddependency-check.skip=true --projects exist-xqts --also-make
      - name: Run XQTS
        timeout-minutes: 60
        env:
          JAVA_OPTS: -XX:+UseZGC
        run: find exist-xqts/target -name exist-xqts-runner.sh -exec {} --xqts-version HEAD --output-dir /tmp/xqts-output \;
      - name: Archive XQTS Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xqts-logs
          retention-days: 14
          path: /tmp/xqts-output
      - name: Get Previous XQTS Logs Artifacts JSON
        run: 'curl -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/exist-db/exist/actions/artifacts?name=xqts-logs > /tmp/previous-xqts-logs-artifacts.json'
      - name: Extract Previous XQTS Logs Artifact JSON
        run: cat /tmp/previous-xqts-logs-artifacts.json | jq -r "[.artifacts[] | select(.workflow_run.head_branch == \"develop\")][1].archive_download_url" > /tmp/previous-xqts-logs-artifact.json
      - name: Get Previous XQTS Logs Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 'cat /tmp/previous-xqts-logs-artifact.json | xargs curl -H "Authorization: Bearer ${GITHUB_TOKEN}" --output /tmp/previous-xqts-output.zip'
      - name: Extract Previous XQTS Logs
        run: mkdir /tmp/previous-xqts-output && cd /tmp/previous-xqts-output && unzip /tmp/previous-xqts-output.zip

