name: XQTS
on: [push, pull_request]
jobs:
  xqts:
    name: W3C XQuery Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'
      - name: Maven Build
        timeout-minutes: 60
        run: mvn -V -B clean package -DskipTests -Ddependency-check.skip=true -Ddocker=false -P !mac-dmg-on-unix,!installer,!concurrency-stress-tests,!micro-benchmarks,!build-dist-archives
      - name: Run XQTS
        run: find exist-xqts/target -name exist-xqts-runner.sh -exec {} --xqts-version HEAD --output-dir /tmp/xqts-output \;
      - name: Archive XQTS Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: xqts-logs
          retention-days: 14
          path: /tmp/xqts-output
