name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    name: Build and Test (${{ matrix.os }} / OpenJDK ${{ matrix.jdk }})
    strategy:
      fail-fast: true
      matrix:
        jdk: ['8', '11', '15']
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Build
        run: mvn -V -B -DskipTests=true "-Dmaven.javadoc.skip=true" install
      - name: Maven Test
        run: mvn -V -B verify -Ptests
      - name: Maven Javadoc
        Run: mvn -V -B javadoc:javadoc
