name: CI
on: [push, pull_request]
jobs:
  build:
    name: (${{ matrix.os }} / JDK ${{ matrix.jdk }} / Docker Image ${{ matrix.build-docker-image }}) Build and Test
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        jdk: ['8', '11']
        build-docker-image: [false]
        include:
          # Also build on JDK 15 on Ubuntu (experimental)
          - os: ubuntu-latest
            jdk: 15
          # Only build our Docker Image on Ubuntu / JDK 8
          - os: ubuntu-latest
            jdk: 8
            build-docker-image: true
        exclude:
          - os: ubuntu-latest
            jdk: 8
            build-docker-image: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
# NOTE(AR) The `-T 2C` enables multi-threaded builds below, faster, but may need to be disabled when diagnosing problems
      - name: Maven Build
        run: mvn -V -B -q -T 2C -DskipTests=true "-Dmaven.javadoc.skip=true" -Ddocker=${{ matrix.build-docker-image }} install
      - name: Maven Test
        run: mvn -V -B "-Dsurefire.useFile=false" -DtrimStackTrace=false test
      - name: Maven License Check
        run: mvn -V -B license:check
# TODO(AR) test and license:check should be replaced by verify, but seems to cause an error on GitHub Actions
#      - name: Maven Verify
#        run: mvn -V -B verify
      - name: Maven Javadoc
        run: mvn -V -B -q -T 2C javadoc:javadoc
      - name: Publish Latest Docker Images
        if: matrix.build-docker-image == true && github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: exist-docker
        run: mvn -Ddocker.tag=latest -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:push
      - name: Publish Release Docker Images
        if: matrix.build-docker-image == true && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: exist-docker
        run: mvn -Ddocker.tag=release -Ddocker.username=$DOCKER_USERNAME -Ddocker.password=$DOCKER_PASSWORD docker:push